### ISSUE TITLE
Excessive requests to youtube

### ISSUE THREAD

**Issue by gdw2** [jichu4n/asciidoclive#23]
I was using the network inspector while using asciidoclive.com and noticed that several requests are made to youtube.com on every keystroke:

![image](https://user-images.githubusercontent.com/665024/71023786-b292db80-20c0-11ea-9b35-641b5e80bce5.png)

Is there a reason to do so?  If not, I'd consider this a bug.

**Comment by jichu4n** [comment]
Thanks - this is because the initial placeholder text embeds a YouTube video: 
![image](https://user-images.githubusercontent.com/326631/71235711-ccdfdb80-22b1-11ea-8c85-f67921b333c0.png) When you change the text on the left (without removing the YouTube video embed), the preview gets updated and the YouTube video gets reloaded as a result. It would stop loading the video if you clear out the placeholder text on the left or replace it with your own content.

**Comment by gdw2** [comment]
Ha ha. Makes sense.
